TYPE=VIEW
query=select `cbwebca_bd01`.`objectif_valeur`.`objectif_valeur_id` AS `objectif_valeur_id`,`cbwebca_bd01`.`objectif`.`objectif_id` AS `objectif_id`,`cbwebca_bd01`.`objectif_valeur`.`effectif_date` AS `effectif_date`,`cbwebca_bd01`.`objectif_valeur`.`cible` AS `cible`,`cbwebca_bd01`.`objectif_valeur`.`sens` AS `sens`,`cbwebca_bd01`.`objectif_valeur`.`valeur` AS `valeur`,`cbwebca_bd01`.`objectif_valeur`.`valeur` / `cbwebca_bd01`.`objectif_valeur`.`cible` AS `cible_completion`,`dern_objectif_valeur`.`effectif_date` AS `dern_effectif_date`,`dern_objectif_valeur`.`cible` AS `dern_cible`,`dern_objectif_valeur`.`sens` AS `dern_sens`,`dern_objectif_valeur`.`valeur` AS `dern_valeur`,`cbwebca_bd01`.`objectif`.`code` AS `code`,`cbwebca_bd01`.`objectif`.`libelle` AS `libelle` from ((`cbwebca_bd01`.`objectif_valeur` join `cbwebca_bd01`.`objectif` on(`cbwebca_bd01`.`objectif`.`objectif_id` = `cbwebca_bd01`.`objectif_valeur`.`objectif_id`)) left join `cbwebca_bd01`.`objectif_valeur` `dern_objectif_valeur` on(`dern_objectif_valeur`.`objectif_id` = `cbwebca_bd01`.`objectif`.`objectif_id` and `dern_objectif_valeur`.`objectif_valeur_id` = (select `ov2`.`objectif_valeur_id` from `cbwebca_bd01`.`objectif_valeur` `ov2` where `ov2`.`objectif_id` = `cbwebca_bd01`.`objectif`.`objectif_id` and `ov2`.`objectif_valeur_id` <> `cbwebca_bd01`.`objectif_valeur`.`objectif_valeur_id` and `ov2`.`effectif_date` < `cbwebca_bd01`.`objectif_valeur`.`effectif_date` order by `ov2`.`effectif_date` desc limit 1)))
md5=e71bb03c4c669b659f26d3dbaa4a7db2
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2021-11-22 19:39:28
create-version=2
source=SELECT		objectif_valeur.objectif_valeur_id\n                ,objectif.objectif_id\n                ,objectif_valeur.effectif_date\n                ,objectif_valeur.cible\n                ,objectif_valeur.sens\n                ,objectif_valeur.valeur\n                ,( objectif_valeur.valeur / objectif_valeur.cible ) AS cible_completion\n				,dern_objectif_valeur.effectif_date AS dern_effectif_date\n				,dern_objectif_valeur.cible AS dern_cible\n				,dern_objectif_valeur.sens AS dern_sens\n				,dern_objectif_valeur.valeur AS dern_valeur\n				,objectif.code\n				,objectif.libelle\n	FROM		objectif_valeur \n    JOIN        objectif ON objectif.objectif_id = objectif_valeur.objectif_id\n	LEFT JOIN	objectif_valeur dern_objectif_valeur ON dern_objectif_valeur.objectif_id = objectif.objectif_id AND\n														dern_objectif_valeur.objectif_valeur_id = ( SELECT 		OV2.objectif_valeur_id\n																									FROM		objectif_valeur OV2\n																									WHERE		OV2.objectif_id = objectif.objectif_id\n																									AND			OV2.objectif_valeur_id != objectif_valeur.objectif_valeur_id\n																									AND			OV2.effectif_date < objectif_valeur.effectif_date\n																									ORDER BY	OV2.effectif_date DESC\n																									LIMIT 		1 )
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select `cbwebca_bd01`.`objectif_valeur`.`objectif_valeur_id` AS `objectif_valeur_id`,`cbwebca_bd01`.`objectif`.`objectif_id` AS `objectif_id`,`cbwebca_bd01`.`objectif_valeur`.`effectif_date` AS `effectif_date`,`cbwebca_bd01`.`objectif_valeur`.`cible` AS `cible`,`cbwebca_bd01`.`objectif_valeur`.`sens` AS `sens`,`cbwebca_bd01`.`objectif_valeur`.`valeur` AS `valeur`,`cbwebca_bd01`.`objectif_valeur`.`valeur` / `cbwebca_bd01`.`objectif_valeur`.`cible` AS `cible_completion`,`dern_objectif_valeur`.`effectif_date` AS `dern_effectif_date`,`dern_objectif_valeur`.`cible` AS `dern_cible`,`dern_objectif_valeur`.`sens` AS `dern_sens`,`dern_objectif_valeur`.`valeur` AS `dern_valeur`,`cbwebca_bd01`.`objectif`.`code` AS `code`,`cbwebca_bd01`.`objectif`.`libelle` AS `libelle` from ((`cbwebca_bd01`.`objectif_valeur` join `cbwebca_bd01`.`objectif` on(`cbwebca_bd01`.`objectif`.`objectif_id` = `cbwebca_bd01`.`objectif_valeur`.`objectif_id`)) left join `cbwebca_bd01`.`objectif_valeur` `dern_objectif_valeur` on(`dern_objectif_valeur`.`objectif_id` = `cbwebca_bd01`.`objectif`.`objectif_id` and `dern_objectif_valeur`.`objectif_valeur_id` = (select `ov2`.`objectif_valeur_id` from `cbwebca_bd01`.`objectif_valeur` `ov2` where `ov2`.`objectif_id` = `cbwebca_bd01`.`objectif`.`objectif_id` and `ov2`.`objectif_valeur_id` <> `cbwebca_bd01`.`objectif_valeur`.`objectif_valeur_id` and `ov2`.`effectif_date` < `cbwebca_bd01`.`objectif_valeur`.`effectif_date` order by `ov2`.`effectif_date` desc limit 1)))
mariadb-version=100508
