TYPE=VIEW
query=select `cbwebca_bd01`.`objectif_suivi`.`objectif_suivi_id` AS `objectif_suivi_id`,`cbwebca_bd01`.`objectif_suivi`.`objectif_id` AS `objectif_id`,`cbwebca_bd01`.`objectif_suivi`.`creation_date` AS `creation_date`,`cbwebca_bd01`.`objectif_suivi`.`note` AS `note`,`cbwebca_bd01`.`objectif_suivi`.`echeance_date` AS `echeance_date`,`cbwebca_bd01`.`objectif_suivi`.`responsable_personnel_id` AS `responsable_personnel_id`,`cbwebca_bd01`.`objectif_suivi`.`termine_date` AS `termine_date`,`v_objectif`.`libelle` AS `objectif_libelle`,`v_objectif`.`code` AS `objectif_code`,`cbwebca_bd01`.`departement`.`departement_id` AS `responsable_departement_id`,`cbwebca_bd01`.`departement`.`direction_id` AS `responsable_direction_id`,concat(rtrim(`cbwebca_bd01`.`personnel`.`nom`),\', \',`cbwebca_bd01`.`personnel`.`prenom`) AS `responsable_personnel_libelle`,if(`cbwebca_bd01`.`objectif_suivi`.`termine_date` is not null,\'Terminé\',if(`cbwebca_bd01`.`objectif_suivi`.`echeance_date` <= curdate(),\'En retard\',\'À faire\')) AS `ind_statut`,if(`cbwebca_bd01`.`objectif_suivi`.`termine_date` is null,1,0) AS `ind_a_faire` from (((`cbwebca_bd01`.`objectif_suivi` left join `cbwebca_bd01`.`v_objectif` on(`v_objectif`.`objectif_id` = `cbwebca_bd01`.`objectif_suivi`.`objectif_id`)) left join `cbwebca_bd01`.`personnel` on(`cbwebca_bd01`.`personnel`.`personnel_id` = `cbwebca_bd01`.`objectif_suivi`.`responsable_personnel_id`)) left join `cbwebca_bd01`.`departement` on(`cbwebca_bd01`.`departement`.`departement_id` = `cbwebca_bd01`.`personnel`.`departement_id`))
md5=d93162172179ae4a1366ce3b4be8dd86
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2021-11-22 23:37:10
create-version=2
source=SELECT		objectif_suivi.*\n				,v_objectif.libelle AS objectif_libelle\n				,v_objectif.code AS objectif_code\n				,departement.departement_id AS responsable_departement_id\n				,departement.direction_id AS responsable_direction_id\n				,CONCAT( RTRIM( personnel.nom ), \', \', personnel.prenom ) AS responsable_personnel_libelle\n				,IF( termine_date IS NOT NULL, \'Terminé\', IF( echeance_date <= CURDATE(), \'En retard\', \'À faire\' ) ) AS ind_statut \n				,IF( termine_date IS NULL, 1, 0 ) AS ind_a_faire\n	FROM		objectif_suivi\n	LEFT JOIN	v_objectif ON v_objectif.objectif_id = objectif_suivi.objectif_id\n	LEFT JOIN	personnel ON personnel.personnel_id = objectif_suivi.responsable_personnel_id\n	LEFT JOIN	departement ON departement.departement_id = personnel.departement_id
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select `cbwebca_bd01`.`objectif_suivi`.`objectif_suivi_id` AS `objectif_suivi_id`,`cbwebca_bd01`.`objectif_suivi`.`objectif_id` AS `objectif_id`,`cbwebca_bd01`.`objectif_suivi`.`creation_date` AS `creation_date`,`cbwebca_bd01`.`objectif_suivi`.`note` AS `note`,`cbwebca_bd01`.`objectif_suivi`.`echeance_date` AS `echeance_date`,`cbwebca_bd01`.`objectif_suivi`.`responsable_personnel_id` AS `responsable_personnel_id`,`cbwebca_bd01`.`objectif_suivi`.`termine_date` AS `termine_date`,`v_objectif`.`libelle` AS `objectif_libelle`,`v_objectif`.`code` AS `objectif_code`,`cbwebca_bd01`.`departement`.`departement_id` AS `responsable_departement_id`,`cbwebca_bd01`.`departement`.`direction_id` AS `responsable_direction_id`,concat(rtrim(`cbwebca_bd01`.`personnel`.`nom`),\', \',`cbwebca_bd01`.`personnel`.`prenom`) AS `responsable_personnel_libelle`,if(`cbwebca_bd01`.`objectif_suivi`.`termine_date` is not null,\'Terminé\',if(`cbwebca_bd01`.`objectif_suivi`.`echeance_date` <= curdate(),\'En retard\',\'À faire\')) AS `ind_statut`,if(`cbwebca_bd01`.`objectif_suivi`.`termine_date` is null,1,0) AS `ind_a_faire` from (((`cbwebca_bd01`.`objectif_suivi` left join `cbwebca_bd01`.`v_objectif` on(`v_objectif`.`objectif_id` = `cbwebca_bd01`.`objectif_suivi`.`objectif_id`)) left join `cbwebca_bd01`.`personnel` on(`cbwebca_bd01`.`personnel`.`personnel_id` = `cbwebca_bd01`.`objectif_suivi`.`responsable_personnel_id`)) left join `cbwebca_bd01`.`departement` on(`cbwebca_bd01`.`departement`.`departement_id` = `cbwebca_bd01`.`personnel`.`departement_id`))
mariadb-version=100508
