TYPE=VIEW
query=select `v_plan`.`plan_id` AS `plan_id`,`v_plan`.`objectif_id` AS `objectif_id`,`v_plan`.`plan_code_wbs` AS `plan_code_wbs`,`v_plan`.`plan_niveau_1` AS `plan_niveau_1`,`v_plan`.`plan_niveau_2` AS `plan_niveau_2`,`v_plan`.`plan_niveau_3` AS `plan_niveau_3`,`v_plan`.`plan_niveau_4` AS `plan_niveau_4`,`v_plan`.`plan_niveau_5` AS `plan_niveau_5`,`v_plan`.`plan_niveau_6` AS `plan_niveau_6`,`v_plan`.`plan_niveau_7` AS `plan_niveau_7`,`v_plan`.`code_wbs` AS `code_wbs`,`v_plan`.`niveau` AS `niveau`,`v_plan`.`poids` AS `poids`,`v_plan`.`type_objectif_classe` AS `type_element_classe`,`v_plan`.`type_objectif_libelle` AS `type_element_libelle`,`v_plan`.`type_objectif_code` AS `type_element_code`,`v_plan`.`libelle` AS `libelle`,`v_plan`.`attributs_desc` AS `attributs`,`v_plan`.`responsable_nom` AS `responsable_nom`,`v_plan`.`responsable_prenom` AS `responsable_prenom`,`v_plan`.`responsable_courriel` AS `responsable_courriel`,`v_plan`.`responsable_departement_code` AS `responsable_departement_code`,`v_plan`.`responsable_direction_code` AS `responsable_direction_code`,`v_plan`.`cible` AS `cible`,`v_plan`.`valeur` AS `valeur`,`v_plan`.`sens` AS `sens`,`v_plan`.`cible_ecart` AS `cible_ecart`,`v_plan`.`decompte` AS `decompte`,`v_plan`.`termine_decompte` AS `termine_decompte`,`v_plan`.`termine_pourcent` / 100.0 AS `termine_pourcent`,`v_plan`.`completion_pourcent` / 100.0 AS `completion_pourcent`,`v_plan`.`debut_date` AS `estime_debut_date`,`v_plan`.`fin_date` AS `estime_fin_date`,`v_plan`.`reddition_debut_date` AS `reddition_debut_date`,`v_plan`.`reddition_fin_date` AS `reddition_fin_date`,`v_plan`.`duree` AS `duree`,`v_plan`.`jours_restants` AS `jours_restants`,`v_plan`.`cycle_pourcent` / 100.0 AS `cycle_pourcent`,`v_plan`.`budget_total` AS `budget_total`,`v_plan`.`budget_depense` AS `budget_depense`,`v_plan`.`budget_engage` AS `budget_engage`,`v_plan`.`budget_pourcent` / 100.0 AS `budget_pourcent`,`v_plan`.`statut` AS `statut`,`v_plan`.`reddition_date` AS `reddition_date`,`v_plan`.`budget_effectif_date` AS `budget_effectif_date`,`v_plan`.`codes_reddition_codes_desc` AS `codes_reddition`,case when exists(select 1 from ((`cbwebca_bd01`.`reddition_a_faire` join `cbwebca_bd01`.`reddition` on(`cbwebca_bd01`.`reddition`.`reddition_id` = `cbwebca_bd01`.`reddition_a_faire`.`reddition_id`)) left join `cbwebca_bd01`.`objectif_reddition` on(`cbwebca_bd01`.`objectif_reddition`.`objectif_id` = `cbwebca_bd01`.`reddition_a_faire`.`objectif_id` and `cbwebca_bd01`.`objectif_reddition`.`reddition_date` between `cbwebca_bd01`.`reddition`.`debut_date` and `cbwebca_bd01`.`reddition`.`fin_date`)) where `cbwebca_bd01`.`reddition_a_faire`.`objectif_id` = `v_plan`.`objectif_id` and `cbwebca_bd01`.`objectif_reddition`.`objectif_reddition_id` is null limit 1) then 1 else 0 end AS `reddition_a_faire`,ifnull(`v_plan`.`ind_termine`,0) AS `est_termine` from `cbwebca_bd01`.`v_plan` where `v_plan`.`code_wbs` is not null
md5=123cff89381826a06ccc56f58a805740
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2021-11-22 23:35:41
create-version=2
source=SELECT		v_plan.plan_id\n				,v_plan.objectif_id\n\n				,v_plan.plan_code_wbs\n\n				,v_plan.plan_niveau_1\n				,v_plan.plan_niveau_2\n				,v_plan.plan_niveau_3\n				,v_plan.plan_niveau_4\n				,v_plan.plan_niveau_5\n				,v_plan.plan_niveau_6\n				,v_plan.plan_niveau_7\n				\n				,v_plan.code_wbs\n				,v_plan.niveau\n				,v_plan.poids\n				,v_plan.type_objectif_classe AS type_element_classe\n				,v_plan.type_objectif_libelle AS type_element_libelle\n				,v_plan.type_objectif_code AS type_element_code\n				,v_plan.libelle\n				,v_plan.attributs_desc AS attributs\n				,v_plan.responsable_nom\n				,v_plan.responsable_prenom\n				,v_plan.responsable_courriel\n				,v_plan.responsable_departement_code\n				,v_plan.responsable_direction_code\n				\n				,v_plan.cible\n				,v_plan.valeur\n				,v_plan.sens\n				,v_plan.cible_ecart\n					\n				,v_plan.decompte\n				,v_plan.termine_decompte\n				,( v_plan.termine_pourcent / 100.0 ) AS termine_pourcent\n				,( v_plan.completion_pourcent / 100.0 ) AS completion_pourcent\n				\n				,v_plan.debut_date AS estime_debut_date\n				,v_plan.fin_date AS estime_fin_date\n				,v_plan.reddition_debut_date\n				,v_plan.reddition_fin_date\n				,v_plan.duree\n				,v_plan.jours_restants\n				,( v_plan.cycle_pourcent / 100.0 ) AS cycle_pourcent\n				\n				,v_plan.budget_total\n				,v_plan.budget_depense\n				,v_plan.budget_engage\n				,( v_plan.budget_pourcent / 100.0 ) AS budget_pourcent\n				\n				,v_plan.statut\n				,v_plan.reddition_date\n				,v_plan.budget_effectif_date\n				,v_plan.codes_reddition_codes_desc AS codes_reddition\n\n				,CASE WHEN EXISTS (	SELECT 		1 \n									FROM 		reddition_a_faire\n									JOIN		reddition ON reddition.reddition_id = reddition_a_faire.reddition_id\n									LEFT JOIN 	objectif_reddition ON 	objectif_reddition.objectif_id = reddition_a_faire.objectif_id AND\n																		objectif_reddition.reddition_date BETWEEN reddition.debut_date AND reddition.fin_date\n									WHERE 		reddition_a_faire.objectif_id = v_plan.objectif_id\n									AND			objectif_reddition.objectif_reddition_id IS NULL ) THEN 1 ELSE 0 END AS reddition_a_faire\n\n				,IFNULL( v_plan.ind_termine, 0 ) AS est_termine\n\n	FROM		v_plan\n	WHERE		v_plan.code_wbs IS NOT NULL
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select `v_plan`.`plan_id` AS `plan_id`,`v_plan`.`objectif_id` AS `objectif_id`,`v_plan`.`plan_code_wbs` AS `plan_code_wbs`,`v_plan`.`plan_niveau_1` AS `plan_niveau_1`,`v_plan`.`plan_niveau_2` AS `plan_niveau_2`,`v_plan`.`plan_niveau_3` AS `plan_niveau_3`,`v_plan`.`plan_niveau_4` AS `plan_niveau_4`,`v_plan`.`plan_niveau_5` AS `plan_niveau_5`,`v_plan`.`plan_niveau_6` AS `plan_niveau_6`,`v_plan`.`plan_niveau_7` AS `plan_niveau_7`,`v_plan`.`code_wbs` AS `code_wbs`,`v_plan`.`niveau` AS `niveau`,`v_plan`.`poids` AS `poids`,`v_plan`.`type_objectif_classe` AS `type_element_classe`,`v_plan`.`type_objectif_libelle` AS `type_element_libelle`,`v_plan`.`type_objectif_code` AS `type_element_code`,`v_plan`.`libelle` AS `libelle`,`v_plan`.`attributs_desc` AS `attributs`,`v_plan`.`responsable_nom` AS `responsable_nom`,`v_plan`.`responsable_prenom` AS `responsable_prenom`,`v_plan`.`responsable_courriel` AS `responsable_courriel`,`v_plan`.`responsable_departement_code` AS `responsable_departement_code`,`v_plan`.`responsable_direction_code` AS `responsable_direction_code`,`v_plan`.`cible` AS `cible`,`v_plan`.`valeur` AS `valeur`,`v_plan`.`sens` AS `sens`,`v_plan`.`cible_ecart` AS `cible_ecart`,`v_plan`.`decompte` AS `decompte`,`v_plan`.`termine_decompte` AS `termine_decompte`,`v_plan`.`termine_pourcent` / 100.0 AS `termine_pourcent`,`v_plan`.`completion_pourcent` / 100.0 AS `completion_pourcent`,`v_plan`.`debut_date` AS `estime_debut_date`,`v_plan`.`fin_date` AS `estime_fin_date`,`v_plan`.`reddition_debut_date` AS `reddition_debut_date`,`v_plan`.`reddition_fin_date` AS `reddition_fin_date`,`v_plan`.`duree` AS `duree`,`v_plan`.`jours_restants` AS `jours_restants`,`v_plan`.`cycle_pourcent` / 100.0 AS `cycle_pourcent`,`v_plan`.`budget_total` AS `budget_total`,`v_plan`.`budget_depense` AS `budget_depense`,`v_plan`.`budget_engage` AS `budget_engage`,`v_plan`.`budget_pourcent` / 100.0 AS `budget_pourcent`,`v_plan`.`statut` AS `statut`,`v_plan`.`reddition_date` AS `reddition_date`,`v_plan`.`budget_effectif_date` AS `budget_effectif_date`,`v_plan`.`codes_reddition_codes_desc` AS `codes_reddition`,case when exists(select 1 from ((`cbwebca_bd01`.`reddition_a_faire` join `cbwebca_bd01`.`reddition` on(`cbwebca_bd01`.`reddition`.`reddition_id` = `cbwebca_bd01`.`reddition_a_faire`.`reddition_id`)) left join `cbwebca_bd01`.`objectif_reddition` on(`cbwebca_bd01`.`objectif_reddition`.`objectif_id` = `cbwebca_bd01`.`reddition_a_faire`.`objectif_id` and `cbwebca_bd01`.`objectif_reddition`.`reddition_date` between `cbwebca_bd01`.`reddition`.`debut_date` and `cbwebca_bd01`.`reddition`.`fin_date`)) where `cbwebca_bd01`.`reddition_a_faire`.`objectif_id` = `v_plan`.`objectif_id` and `cbwebca_bd01`.`objectif_reddition`.`objectif_reddition_id` is null limit 1) then 1 else 0 end AS `reddition_a_faire`,ifnull(`v_plan`.`ind_termine`,0) AS `est_termine` from `cbwebca_bd01`.`v_plan` where `v_plan`.`code_wbs` is not null
mariadb-version=100508
