TYPE=VIEW
query=select `cbwebca_bd01`.`plan`.`plan_id` AS `plan_id`,`cbwebca_bd01`.`plan`.`parent_id` AS `parent_id`,`cbwebca_bd01`.`plan`.`objectif_id` AS `objectif_id`,`cbwebca_bd01`.`plan`.`code` AS `code`,`cbwebca_bd01`.`plan`.`poids` AS `poids`,`cbwebca_bd01`.`plan`.`note` AS `note`,`cbwebca_bd01`.`plan`.`code_wbs` AS `code_wbs`,`v_objectif`.`type_objectif_code` AS `type_objectif_code`,`v_objectif`.`type_objectif_css` AS `type_objectif_css`,`v_objectif`.`type_objectif_classe` AS `type_objectif_classe`,`v_objectif`.`libelle` AS `libelle`,`v_objectif`.`code` AS `objectif_code`,`v_objectif`.`attributs` AS `attributs`,`v_objectif`.`responsable_personnel_id` AS `responsable_personnel_id`,`v_objectif`.`responsable_nom` AS `responsable_nom`,`v_objectif`.`responsable_prenom` AS `responsable_prenom`,`v_objectif`.`responsable_departement_code` AS `responsable_departement_code`,`v_objectif`.`plan_decompte` AS `plan_decompte`,(select count(0) from `cbwebca_bd01`.`plan` `a` where `a`.`parent_id` = `cbwebca_bd01`.`plan`.`plan_id`) AS `plan_enfant_decompte`,`v_objectif`.`cible_completion` AS `cible_completion`,case when `v_objectif`.`reddition_date` is not null then `v_objectif`.`jours_restants` else case when to_days(`cbwebca_bd01`.`plan`.`fin_date`) - to_days(`cbwebca_bd01`.`plan`.`reddition_date`) < 0 then 0 else to_days(`cbwebca_bd01`.`plan`.`fin_date`) - to_days(`cbwebca_bd01`.`plan`.`reddition_date`) end end AS `jours_restants`,case when `v_objectif`.`reddition_date` is not null then `v_objectif`.`cycle_pourcent` else case when round((to_days(`cbwebca_bd01`.`plan`.`fin_date`) - to_days(`cbwebca_bd01`.`plan`.`reddition_date`)) * 100 / (to_days(`cbwebca_bd01`.`plan`.`fin_date`) - to_days(`cbwebca_bd01`.`plan`.`reddition_debut_date`)),0) < 0 then 0 else round((to_days(`cbwebca_bd01`.`plan`.`fin_date`) - to_days(`cbwebca_bd01`.`plan`.`reddition_date`)) * 100 / (to_days(`cbwebca_bd01`.`plan`.`fin_date`) - to_days(`cbwebca_bd01`.`plan`.`reddition_debut_date`)),0) end end AS `cycle_pourcent`,case when `v_objectif`.`reddition_date` is not null then `v_objectif`.`completion_pourcent` else round(`cbwebca_bd01`.`plan`.`completion_pourcent_total` / `cbwebca_bd01`.`plan`.`decompte`,0) end AS `completion_pourcent`,case when `v_objectif`.`budget_effectif_date` is not null then round((`v_objectif`.`budget_depense` + `v_objectif`.`budget_engage`) * 100 / `v_objectif`.`budget_total`,0) else round((`cbwebca_bd01`.`plan`.`budget_depense` + `cbwebca_bd01`.`plan`.`budget_engage`) * 100 / `cbwebca_bd01`.`plan`.`budget_total`,0) end AS `budget_pourcent`,`cbwebca_bd01`.`statut`.`statut_id` AS `statut_id`,`cbwebca_bd01`.`statut`.`css` AS `statut_css`,`cbwebca_bd01`.`statut`.`libelle` AS `statut` from ((`cbwebca_bd01`.`plan` join `cbwebca_bd01`.`v_objectif` on(`v_objectif`.`objectif_id` = `cbwebca_bd01`.`plan`.`objectif_id`)) left join `cbwebca_bd01`.`statut` on(`cbwebca_bd01`.`statut`.`statut_id` = `cbwebca_bd01`.`plan`.`z_statut_id`))
md5=5288170ffab1f329cb8fa31c18e7d6b1
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2021-11-22 23:35:42
create-version=2
source=SELECT		plan.plan_id\n				,plan.parent_id\n				,plan.objectif_id\n				,plan.code\n				,plan.poids\n				,plan.note\n\n				,plan.code_wbs\n\n				,v_objectif.type_objectif_code\n				,v_objectif.type_objectif_css\n				,v_objectif.type_objectif_classe\n\n				,v_objectif.libelle\n\n				,v_objectif.code AS objectif_code\n\n				,v_objectif.attributs\n\n				,v_objectif.responsable_personnel_id\n				,v_objectif.responsable_nom\n				,v_objectif.responsable_prenom\n				,v_objectif.responsable_departement_code\n\n				,v_objectif.plan_decompte\n\n				,( SELECT COUNT(*) FROM plan A WHERE A.parent_id = plan.plan_id ) AS plan_enfant_decompte\n\n				,v_objectif.cible_completion\n\n				,CASE\n					WHEN v_objectif.reddition_date IS NOT NULL THEN v_objectif.jours_restants\n					ELSE \n						CASE \n							WHEN DATEDIFF( plan.fin_date, plan.reddition_date ) < 0 THEN 0\n							ELSE DATEDIFF( plan.fin_date, plan.reddition_date )\n						END\n				END AS jours_restants\n\n				,CASE\n					WHEN v_objectif.reddition_date IS NOT NULL\n					THEN v_objectif.cycle_pourcent\n					ELSE \n						CASE \n							WHEN ROUND( DATEDIFF( plan.fin_date, plan.reddition_date ) * 100 / DATEDIFF( plan.fin_date, plan.reddition_debut_date ), 0 ) < 0 THEN 0\n							ELSE ROUND( DATEDIFF( plan.fin_date, plan.reddition_date ) * 100 / DATEDIFF( plan.fin_date, plan.reddition_debut_date ), 0 )\n						END\n				END AS cycle_pourcent\n\n				,CASE\n					WHEN v_objectif.reddition_date IS NOT NULL\n					THEN v_objectif.completion_pourcent \n					ELSE ROUND( ( plan.completion_pourcent_total ) / plan.decompte, 0 ) \n				END AS completion_pourcent\n\n				,CASE\n					WHEN v_objectif.budget_effectif_date IS NOT NULL\n					THEN ROUND( ( v_objectif.budget_depense + v_objectif.budget_engage ) * 100 / v_objectif.budget_total, 0 )  \n					ELSE ROUND( ( plan.budget_depense + plan.budget_engage ) * 100 / plan.budget_total, 0 ) \n				END AS budget_pourcent\n\n				,statut.statut_id\n				,statut.css AS statut_css\n				,statut.libelle AS statut\n\n	FROM		plan\n	JOIN   		v_objectif 	ON v_objectif.objectif_id = plan.objectif_id\n	LEFT JOIN	statut ON statut.statut_id = plan.z_statut_id
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select `cbwebca_bd01`.`plan`.`plan_id` AS `plan_id`,`cbwebca_bd01`.`plan`.`parent_id` AS `parent_id`,`cbwebca_bd01`.`plan`.`objectif_id` AS `objectif_id`,`cbwebca_bd01`.`plan`.`code` AS `code`,`cbwebca_bd01`.`plan`.`poids` AS `poids`,`cbwebca_bd01`.`plan`.`note` AS `note`,`cbwebca_bd01`.`plan`.`code_wbs` AS `code_wbs`,`v_objectif`.`type_objectif_code` AS `type_objectif_code`,`v_objectif`.`type_objectif_css` AS `type_objectif_css`,`v_objectif`.`type_objectif_classe` AS `type_objectif_classe`,`v_objectif`.`libelle` AS `libelle`,`v_objectif`.`code` AS `objectif_code`,`v_objectif`.`attributs` AS `attributs`,`v_objectif`.`responsable_personnel_id` AS `responsable_personnel_id`,`v_objectif`.`responsable_nom` AS `responsable_nom`,`v_objectif`.`responsable_prenom` AS `responsable_prenom`,`v_objectif`.`responsable_departement_code` AS `responsable_departement_code`,`v_objectif`.`plan_decompte` AS `plan_decompte`,(select count(0) from `cbwebca_bd01`.`plan` `a` where `a`.`parent_id` = `cbwebca_bd01`.`plan`.`plan_id`) AS `plan_enfant_decompte`,`v_objectif`.`cible_completion` AS `cible_completion`,case when `v_objectif`.`reddition_date` is not null then `v_objectif`.`jours_restants` else case when to_days(`cbwebca_bd01`.`plan`.`fin_date`) - to_days(`cbwebca_bd01`.`plan`.`reddition_date`) < 0 then 0 else to_days(`cbwebca_bd01`.`plan`.`fin_date`) - to_days(`cbwebca_bd01`.`plan`.`reddition_date`) end end AS `jours_restants`,case when `v_objectif`.`reddition_date` is not null then `v_objectif`.`cycle_pourcent` else case when round((to_days(`cbwebca_bd01`.`plan`.`fin_date`) - to_days(`cbwebca_bd01`.`plan`.`reddition_date`)) * 100 / (to_days(`cbwebca_bd01`.`plan`.`fin_date`) - to_days(`cbwebca_bd01`.`plan`.`reddition_debut_date`)),0) < 0 then 0 else round((to_days(`cbwebca_bd01`.`plan`.`fin_date`) - to_days(`cbwebca_bd01`.`plan`.`reddition_date`)) * 100 / (to_days(`cbwebca_bd01`.`plan`.`fin_date`) - to_days(`cbwebca_bd01`.`plan`.`reddition_debut_date`)),0) end end AS `cycle_pourcent`,case when `v_objectif`.`reddition_date` is not null then `v_objectif`.`completion_pourcent` else round(`cbwebca_bd01`.`plan`.`completion_pourcent_total` / `cbwebca_bd01`.`plan`.`decompte`,0) end AS `completion_pourcent`,case when `v_objectif`.`budget_effectif_date` is not null then round((`v_objectif`.`budget_depense` + `v_objectif`.`budget_engage`) * 100 / `v_objectif`.`budget_total`,0) else round((`cbwebca_bd01`.`plan`.`budget_depense` + `cbwebca_bd01`.`plan`.`budget_engage`) * 100 / `cbwebca_bd01`.`plan`.`budget_total`,0) end AS `budget_pourcent`,`cbwebca_bd01`.`statut`.`statut_id` AS `statut_id`,`cbwebca_bd01`.`statut`.`css` AS `statut_css`,`cbwebca_bd01`.`statut`.`libelle` AS `statut` from ((`cbwebca_bd01`.`plan` join `cbwebca_bd01`.`v_objectif` on(`v_objectif`.`objectif_id` = `cbwebca_bd01`.`plan`.`objectif_id`)) left join `cbwebca_bd01`.`statut` on(`cbwebca_bd01`.`statut`.`statut_id` = `cbwebca_bd01`.`plan`.`z_statut_id`))
mariadb-version=100508
