TYPE=VIEW
query=select `cbwebca_bd01`.`plan`.`objectif_id` AS `objectif_id`,`cbwebca_bd01`.`plan`.`code_wbs` AS `code_wbs`,`cbwebca_bd01`.`objectif`.`type_objectif_id` AS `type_element`,`cbwebca_bd01`.`objectif_personnel`.`personnel_id` AS `responsable`,`cbwebca_bd01`.`departement`.`departement_id` AS `departement`,`cbwebca_bd01`.`direction`.`direction_id` AS `direction`,`cbwebca_bd01`.`objectif`.`libelle` AS `libelle`,`cbwebca_bd01`.`objectif_attribut`.`attribut_id` AS `attribut`,`cbwebca_bd01`.`objectif_reddition`.`completion_pourcent` AS `completion`,`cbwebca_bd01`.`objectif_reddition`.`reddition_date` AS `reddition_date`,`cbwebca_bd01`.`objectif_reddition`.`debut_date` AS `debut_date`,`cbwebca_bd01`.`objectif_reddition`.`fin_date` AS `fin_date`,`cbwebca_bd01`.`objectif_reddition`.`phase_id` AS `phase`,`cbwebca_bd01`.`objectif_reddition`.`z_statut_id` AS `statut` from (((((((`cbwebca_bd01`.`plan` join `cbwebca_bd01`.`objectif` on(`cbwebca_bd01`.`objectif`.`objectif_id` = `cbwebca_bd01`.`plan`.`objectif_id`)) left join `cbwebca_bd01`.`objectif_personnel` on(`cbwebca_bd01`.`objectif_personnel`.`objectif_id` = `cbwebca_bd01`.`objectif`.`objectif_id` and `cbwebca_bd01`.`objectif_personnel`.`responsabilite` = \'R\')) left join `cbwebca_bd01`.`personnel` on(`cbwebca_bd01`.`personnel`.`personnel_id` = `cbwebca_bd01`.`objectif_personnel`.`personnel_id`)) left join `cbwebca_bd01`.`departement` on(`cbwebca_bd01`.`departement`.`departement_id` = `cbwebca_bd01`.`personnel`.`departement_id`)) left join `cbwebca_bd01`.`direction` on(`cbwebca_bd01`.`direction`.`direction_id` = `cbwebca_bd01`.`departement`.`direction_id`)) left join `cbwebca_bd01`.`objectif_attribut` on(`cbwebca_bd01`.`objectif_attribut`.`objectif_id` = `cbwebca_bd01`.`plan`.`objectif_id`)) left join `cbwebca_bd01`.`objectif_reddition` on(`cbwebca_bd01`.`objectif_reddition`.`objectif_id` = `cbwebca_bd01`.`objectif`.`objectif_id` and `cbwebca_bd01`.`objectif_reddition`.`objectif_reddition_id` = (select `cbwebca_bd01`.`objectif_reddition`.`objectif_reddition_id` from `cbwebca_bd01`.`objectif_reddition` where `cbwebca_bd01`.`objectif_reddition`.`objectif_id` = `cbwebca_bd01`.`objectif`.`objectif_id` order by `cbwebca_bd01`.`objectif_reddition`.`reddition_date` desc limit 1)))
md5=9a4edb190fc08978dcaec6a01418735b
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2021-11-24 19:09:05
create-version=2
source=SELECT		plan.objectif_id\n				,plan.code_wbs\n				,objectif.type_objectif_id AS type_element\n				,objectif_personnel.personnel_id AS responsable\n				,departement.departement_id AS departement\n				,direction.direction_id AS direction\n				,objectif.libelle AS libelle\n				,objectif_attribut.attribut_id AS attribut\n				,objectif_reddition.completion_pourcent AS completion\n                ,objectif_reddition.reddition_date\n               	,objectif_reddition.debut_date AS debut_date\n                ,objectif_reddition.fin_date AS fin_date\n				,objectif_reddition.phase_id AS phase\n				,objectif_reddition.z_statut_id AS statut\n				-- ,v_objectif.cycle AS cycle\n				-- ,v_objectif.jours_restants AS jours_restants\n				-- ,v_objectif.debut_date AS debut_date\n				-- ,v_objectif.fin_date AS fin_date\n	FROM		plan\n	JOIN		objectif 				ON  objectif.objectif_id = plan.objectif_id\n	LEFT JOIN	objectif_personnel		ON 	objectif_personnel.objectif_id = objectif.objectif_id AND responsabilite = \'R\' \n	LEFT JOIN	personnel				ON	personnel.personnel_id = objectif_personnel.personnel_id\n	LEFT JOIN   departement             ON  departement.departement_id = personnel.departement_id\n	LEFT JOIN   direction             	ON  direction.direction_id = departement.direction_id\n	LEFT JOIN	objectif_attribut 		ON  objectif_attribut.objectif_id = plan.objectif_id\n    LEFT JOIN   objectif_reddition      ON  objectif_reddition.objectif_id = objectif.objectif_id AND\n                                            objectif_reddition.objectif_reddition_id =  (	SELECT      objectif_reddition.objectif_reddition_id\n																							FROM        objectif_reddition\n																							WHERE       objectif_reddition.objectif_id = objectif.objectif_id\n																							ORDER BY    objectif_reddition.reddition_date DESC\n																							LIMIT       1 )
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select `cbwebca_bd01`.`plan`.`objectif_id` AS `objectif_id`,`cbwebca_bd01`.`plan`.`code_wbs` AS `code_wbs`,`cbwebca_bd01`.`objectif`.`type_objectif_id` AS `type_element`,`cbwebca_bd01`.`objectif_personnel`.`personnel_id` AS `responsable`,`cbwebca_bd01`.`departement`.`departement_id` AS `departement`,`cbwebca_bd01`.`direction`.`direction_id` AS `direction`,`cbwebca_bd01`.`objectif`.`libelle` AS `libelle`,`cbwebca_bd01`.`objectif_attribut`.`attribut_id` AS `attribut`,`cbwebca_bd01`.`objectif_reddition`.`completion_pourcent` AS `completion`,`cbwebca_bd01`.`objectif_reddition`.`reddition_date` AS `reddition_date`,`cbwebca_bd01`.`objectif_reddition`.`debut_date` AS `debut_date`,`cbwebca_bd01`.`objectif_reddition`.`fin_date` AS `fin_date`,`cbwebca_bd01`.`objectif_reddition`.`phase_id` AS `phase`,`cbwebca_bd01`.`objectif_reddition`.`z_statut_id` AS `statut` from (((((((`cbwebca_bd01`.`plan` join `cbwebca_bd01`.`objectif` on(`cbwebca_bd01`.`objectif`.`objectif_id` = `cbwebca_bd01`.`plan`.`objectif_id`)) left join `cbwebca_bd01`.`objectif_personnel` on(`cbwebca_bd01`.`objectif_personnel`.`objectif_id` = `cbwebca_bd01`.`objectif`.`objectif_id` and `cbwebca_bd01`.`objectif_personnel`.`responsabilite` = \'R\')) left join `cbwebca_bd01`.`personnel` on(`cbwebca_bd01`.`personnel`.`personnel_id` = `cbwebca_bd01`.`objectif_personnel`.`personnel_id`)) left join `cbwebca_bd01`.`departement` on(`cbwebca_bd01`.`departement`.`departement_id` = `cbwebca_bd01`.`personnel`.`departement_id`)) left join `cbwebca_bd01`.`direction` on(`cbwebca_bd01`.`direction`.`direction_id` = `cbwebca_bd01`.`departement`.`direction_id`)) left join `cbwebca_bd01`.`objectif_attribut` on(`cbwebca_bd01`.`objectif_attribut`.`objectif_id` = `cbwebca_bd01`.`plan`.`objectif_id`)) left join `cbwebca_bd01`.`objectif_reddition` on(`cbwebca_bd01`.`objectif_reddition`.`objectif_id` = `cbwebca_bd01`.`objectif`.`objectif_id` and `cbwebca_bd01`.`objectif_reddition`.`objectif_reddition_id` = (select `cbwebca_bd01`.`objectif_reddition`.`objectif_reddition_id` from `cbwebca_bd01`.`objectif_reddition` where `cbwebca_bd01`.`objectif_reddition`.`objectif_id` = `cbwebca_bd01`.`objectif`.`objectif_id` order by `cbwebca_bd01`.`objectif_reddition`.`reddition_date` desc limit 1)))
mariadb-version=100508
